// 명령어 데이터
const commands = [
    { title: "모아 키", code: "cheat gfi key 99999999 1 0" },
    { title: "무적", code: "god" },
    { title: "투명화", code: "enemyinvisible true" },
    { title: "투명화 (비활성화)", code: "enemyinvisible false" },
    { title: "경험치", code: "addexperience 10000 0 1" },
    { title: "스탯 무한", code: "infinitestats" },
    { title: "플레이어 앞 공룡 테이밍", code: "dotame" },
    { title: "플레이어 앞 공룡 테이밍 + 안장 없이 탑승 가능", code: "forcetame" },
    { title: "원소 100개", code: "gfi Element 100 0 0" },
    { title: "포드 냉장고", code: "gfi CryoFridge 1 1 0" },
    { title: "크라이포드", code: "gfi EmptyCryopod 100" },
    { title: "테크 발전기", code: "gfi TekGenerator 1 1 0" },
    { title: "날기", code: "fly" },
    { title: "유령화", code: "ghost" },
    { title: "걷기", code: "walk" },
    { title: "모든 앵그램 해금", code: "giveengrams" },
    { title: "강화 무적", code: "gmbuff" },
    { title: "야생 공룡 리셋", code: "DestroyWildDinos" },
    { title: "모든 공룡 리셋", code: "Destroyallenemies" },
    { title: "아기 공룡 성장 수치 조절", code: "SetBabyAge 1" },
    { title: "공룡 각인 수치 설정", code: "SetImprintQuality 1" },
    { title: "공룡들 움직임 멈춤", code: "playersonly" },
    { title: "총알 무제한", code: "toggleinfiniteammo" },
    { title: "모든 자원 얻기", code: "giveresources" },
    { title: "짐승의 유물 얻기", code: "GFI Artifact_12 1 0 0" },
    { title: "짐승의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_12.PrimalItemArtifact_12'\" 1 0 0" },
    { title: "현명한 유물 얻기", code: "GFI Artifact_05 1 0 0" },
    { title: "현명한 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_05.PrimalItemArtifact_05'\" 1 0 0" },
    { title: "교활함의 유물 얻기", code: "GFI Artifact_11 1 0 0" },
    { title: "교활함의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_11.PrimalItemArtifact_11'\" 1 0 0" },
    { title: "탐닉의 유물 얻기", code: "GFI Artifact_07 1 0 0" },
    { title: "탐닉의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_07.PrimalItemArtifact_07'\" 1 0 0" },
    { title: "사냥꾼의 유물 얻기", code: "GFI Artifact_01 1 0 0" },
    { title: "사냥꾼의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_01.PrimalItemArtifact_01'\" 1 0 0" },
    { title: "면역의 유물 얻기", code: "GFI Artifact_08 1 0 0" },
    { title: "면역의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_08.PrimalItemArtifact_08'\" 1 0 0" },
    { title: "거대함의 유물 얻기", code: "GFI Artifact_03 1 0 0" },
    { title: "거대함의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_03.PrimalItemArtifact_03'\" 1 0 0" },
    { title: "무리의 유물 얻기", code: "GFI Artifact_02 1 0 0" },
    { title: "무리의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_02.PrimalItemArtifact_02'\" 1 0 0" },
    { title: "하늘군주의 유물 얻기", code: "GFI Artifact_06 1 0 0" },
    { title: "하늘군주의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_06.PrimalItemArtifact_06'\" 1 0 0" },
    { title: "강함의 유물 얻기", code: "GFI Artifact_09 1 0 0" },
    { title: "강함의 유물 얻기 2", code: "giveitem \"Blueprint'/Game/PrimalEarth/CoreBlueprints/Items/Artifacts/PrimalItemArtifact_09.PrimalItemArtifact_09'\" 1 0 0" },
    { title: "현재 내 버프 지우기", code: "ClearMyBuffs" },
    { title: "테크 슈트 입기", code: "GiveArmorSet Tek 20" },
    { title: "사막 슈트 입기", code: "GiveArmorSet Desert 20" },
    { title: "방호복 슈트 입기", code: "GiveArmorSet Hazard 20" },
    { title: "키틴 슈트 입기", code: "GiveArmorSet Chitin 20" },
    { title: "가죽 슈트 입기", code: "GiveArmorSet Hide 20" },
    { title: "스쿠버 슈트 입기", code: "GiveArmorSet Ghillie 20" },
    { title: "방탄 슈트 입기", code: "GiveArmorSet Scuba 20" },
    { title: "방탄 슈트 입기", code: "GiveArmorSet Metal 20" },
    { title: "모피 슈트 입기", code: "GiveArmorSet Fur 20" },
    { title: "진압복 슈트 입기", code: "GiveArmorSet Riot 20" },
    { title: "천 슈트 입기", code: "GiveArmorSet Cloth 20" },
    { title: "무기 세트 1", code: "GiveWeaponSet 0 20" },
    { title: "무기 세트 2", code: "GiveWeaponSet 1 20" },
    { title: "무기 세트 3", code: "GiveWeaponSet 2 20" },
    { title: "무기 세트 4", code: "GiveWeaponSet 3 20" },
    { title: "아이템 세트 1", code: "GiveItemSet 0" },
    { title: "아이템 세트 2", code: "GiveItemSet 1" },
    { title: "아이템 세트 3", code: "GiveItemSet 2" },
    { title: "아이템 세트 4", code: "GiveItemSet 3" },
    { title: "음식 세트", code: "GiveItemSet food" },
    { title: "수통", code: "GiveItemSet water" },
    { title: "브루 세트", code: "GiveItemSet brews" },
    { title: "관찰자 모드 활성화", code: "Enablespectator" },
    { title: "관찰자 모드 비활성화", code: "Stopspectating" },
    { title: "맵 중앙으로 텔포", code: "teleport" },
    { title: "아일랜드 레드오벨 텔포", code: "tp red" },
    { title: "아일랜드 그린오벨 텔포", code: "tp green" },
    { title: "아일랜드 블루오벨 텔포", code: "tp blue" },
    { title: "아일랜드 동굴 1", code: "tp CAVE1" },
    { title: "아일랜드 동굴 2", code: "tp CAVE2" },
    { title: "아일랜드 동굴 3", code: "tp CAVE3" },
    { title: "아일랜드 동굴 4", code: "tp CAVE4" },
    { title: "아일랜드 동굴 5", code: "tp CAVE5" },
    { title: "아일랜드 동굴 6", code: "tp CAVE6" },
    { title: "아일랜드 동굴 7", code: "tp CAVE7" },
    { title: "아일랜드 동굴 8", code: "tp CAVE8" },
    { title: "아일랜드 동굴 9", code: "tp CAVE9" },
    { title: "아일랜드 동굴 10", code: "tp CAVE10" },
    { title: "스코치드 레드오벨 텔포", code: "tp red" },
    { title: "스코치드 그린오벨 텔포", code: "tp green" },
    { title: "스코치드 블루오벨 텔포", code: "tp blue" },
    { title: "에버레이션 레드오벨 텔포", code: "tp red" },
    { title: "에버레이션 그린오벨 텔포", code: "tp green" },
    { title: "에버레이션 블루오벨 텔포", code: "tp blue" },
    { title: "범위안 안장없이 테이밍", code: "ForceTameAOE 20" },
    { title: "알 즉시 부화", code: "hatchegg" },
    { title: "공룡 세트 1", code: "GiveDinoSet 0 1" },
    { title: "공룡 세트 2", code: "GiveDinoSet 1 1" },
    { title: "공룡 세트 3", code: "GiveDinoSet 2 1" },
    { title: "공룡 세트 4", code: "GiveDinoSet 3 1" },
    { title: "공룡 날탈 세트", code: "GiveDinoSet flyer 1" },
    { title: "공룡 맥 세트", code: "GiveDinoSet mek 1" },
    { title: "아르젠타비스 소환", code: "GiveDinoSet Argent 1" },
    { title: "공룡 익스팅션 세트", code: "GiveDinoSet Extinction 1" },
    { title: "아일랜드 날씨 멈추기", code: "ce stoptime" },
    { title: "아일랜드 날씨 계속하기", code: "ce starttime" },
    { title: "아일랜드 더위 날씨", code: "ce heatwave" },
    { title: "아일랜드 추위 날씨", code: "ce coldfront" },
    { title: "아일랜드 비 날씨", code: "ce makeitrain" },
    { title: "아일랜드 안개 날씨", code: "ce fogitup" },
    { title: "스코치드 어스 폭염 날씨 시작", code: "ce start_superheat" },
    { title: "스코치드 어스 폭염 날씨 멈춤", code: "ce stop_superheat" },
    { title: "스코치드 어스 모래 폭풍 시작", code: "ce start_sandstorm" },
    { title: "스코치드 어스 모래 폭풍 멈춤", code: "ce stop_sandstorm" },
    { title: "스코치드 어스 전기 폭풍 시작", code: "ce start_electricalstorm" },
    { title: "스코치드 어스 전기 폭풍 멈춤", code: "ce stop_electricalstorm" },
    { title: "스코치드 어스 비 시작", code: "ce start_rain" },
    { title: "스코치드 어스 비 멈춤", code: "ce stop_rain" },
    { title: "에버레이션 지진 시작", code: "ce startquake" },
    { title: "에버레이션 지진 멈춤", code: "ce stopquake" },
    { title: "게임 속도", code: "Slomo 4" },
    { title: "인게임 시간 변경", code: "settimeofday 13:30" },
    { title: "아일랜드 감마 래벨", code: "playercommand Ascend1" },
    { title: "아일랜드 베타 래벨", code: "playercommand Ascend2" },
    { title: "아일랜드 알파 래벨", code: "playercommand Ascend3" },
    { title: "에버레이션 감마 래벨", code: "playercommand AbAscend1" },
    { title: "에버레이션 베타 래벨", code: "playercommand AbAscend2" },
    { title: "에버레이션 알파 래벨", code: "playercommand AbAscend3" },
    { title: "바라보는 방향에 경험치 주기", code: "GiveExpToTarget 10000 0 1" },
    { title: "자신에게 데미지 주기", code: "hurtme 1000" },
    { title: "자신에게 힐 하기", code: "hurtme -1000" },
    { title: "바라보는 타겟 죽이기", code: "kill" },
    { title: "범위 근처 모든 공룡 죽이기", code: "KillAOE dinos 3000" },
    { title: "범위 근처 야생 공룡 죽이기", code: "KillAOE wild 3000" },
    { title: "범위 근처 길들인 공룡 죽이기", code: "KillAOE tamed 3000" },
    { title: "범위 근처 플레이어 죽이기", code: "KillAOE players 3000" },
    { title: "범위 근처 구조물 부수기", code: "KillAOE stuctures 3000" },
    { title: "1인칭에서 무기 숨기기", code: "ToggleGun" },
    { title: "서버에 데미지 텍스트 표시", code: "ToggleDamageNumbers" },
    { title: "바실리스크 소환", code: "cheat summon Basilisk_Character_BP_Summoned_C" },
    { title: "블러드스토커", code: "cheat summon BogSpider_Character_BP_Summoned_C" },
    { title: "카르키노스", code: "cheat summon Crab_Character_BP_Summoned_C" },
    { title: "마그마사우르스 소환", code: "cheat summon Cherufe_Character_BP_Summoned_C" },
    { title: "마나가르마", code: "cheat summon IceJumper_Character_BP_Summoned_C" },
    { title: "사마귀 소환", code: "cheat summon Mantis_Character_BP_Summoned_C" },
    { title: "제노모프 수컷(Gen2) 소환", code: "cheat summon Xenomorph_Character_BP_Male_Gen2_Summoned_C" },
    { title: "올빼미 소환", code: "cheat summon Owl_Character_BP_Eden_Summoned_C" },
    { title: "틸라콜레오 소환", code: "cheat summon Thylacoleo_Character_BP_Eden_Summoned_C" },
    { title: "카르키노스 소환", code: "cheat summon Spindles_Character_BP_Rockwell_Summoned_C" },
    { title: "락 드레이크 소환", code: "cheat summon RockDrake_Character_BP_Summoned_C" },
    { title: "케이브 울프", code: "cheat summon CaveWolf_Character_BP_Summoned_C" },
    { title: "락 골렘 소환", code: "cheat summon RockGolem_Character_BP_Summoned_C" },
    { title: "새도우메인", code: "cheat summon LionfishLion_Character_BP_Summoned_C" },




    { title: "아카티나 (달팽이) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Achatina/Achatina_Character_BP.Achatina_Character_BP'" 0 0 0 150` },
    { title: "알로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Allosaurus/Allo_Character_BP.Allo_Character_BP'" 0 0 0 150` },
    { title: "알파 카르노 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Carno/MegaCarno_Character_BP.MegaCarno_Character_BP'" 0 0 0 150` },
    { title: "알파 리드시크티스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Leedsichthys/Alpha_Leedsichthys_Character_BP.Alpha_Leedsichthys_Character_BP'" 0 0 0 150` },
    { title: "알파 메갈로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Megalodon/MEgaMegalodon_Character_BP.MegaMegalodon_Character_BP'" 0 0 0 150` },
    { title: "알파 모사사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP_Mega.Mosa_Character_BP_Mega'" 0 0 0 150` },
    { title: "알파 랩터 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Raptor/MegaRaptor_Character_BP.MegaRaptor_Character_BP'" 0 0 0 150` },
    { title: "알파 티렉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Rex/MegaRex_Character_BP.MegaRex_Character_BP'" 0 0 0 150` },
    { title: "알파 투소테우티스 (알파 크라켄) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Tusoteuthis/Mega_Tusoteuthis_Character_BP.Mega_Tusoteuthis_Character_BP'" 0 0 0 150` },
    { title: "암모나이트 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ammonite/Ammonite_Character.Ammonite_Character'" 0 0 0 150` },
    { title: "앵글러피쉬 (초롱아귀) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Anglerfish/Angler_Character_BP.Angler_Character_BP'" 0 0 0 150` },
    { title: "안킬로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ankylo/Ankylo_Character_BP.Ankylo_Character_BP'" 0 0 0 150` },
    { title: "아라네오 (거미) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Spider-Small/SpiderS_Character_BP.SpiderS_Character_BP'" 0 0 0 150` },
    { title: "아키오프테릭스 (시조새) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Archaeopteryx/Archa_Character_BP.Archa_Character_BP'" 0 0 0 150` },
    { title: "아르젠타비스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP'" 0 0 0 150` },
    { title: "아트로플레우라 (큰 지네) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Arthropluera/Arthro_Character_BP.Arthro_Character_BP'" 0 0 0 150` },
    { title: "바리오닉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_Character_BP.Baryonyx_Character_BP'" 0 0 0 150` },
    { title: "바실로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Basilosaurus/Basilosaurus_Character_BP.Basilosaurus_Character_BP'" 0 0 0 150` },
    { title: "밸제부포 (개구리) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Toad/Toad_Character_BP.Toad_Character_BP'" 0 0 0 150` },
    { title: "브론토사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Sauropod/Sauropod_Character_BP.Sauropod_Character_BP'" 0 0 0 150` },
    { title: "브루드 마더 (거미 보스) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Spider-Large/SpiderL_Character_BP.SpiderL_Character_BP'" 0 0 0 150` },
    { title: "칼리코테리움 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Chalicotherium/Chalico_Character_BP.Chalico_Character_BP'" 0 0 0 150` },
    { title: "카르보네미스 (큰 거북이) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP.Turtle_Character_BP'" 0 0 0 150` },
    { title: "카르노타우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Carno/Carno_Character_BP.Carno_Character_BP'" 0 0 0 150` },
    { title: "카스트로이데스 (비버) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Beaver/Beaver_Character_BP.Beaver_Character_BP'" 0 0 0 150` },
    { title: "해파리 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_Character_BP.Cnidaria_Character_BP'" 0 0 0 150` },
    { title: "실러캔스 (물고기) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP.Coel_Character_BP'" 0 0 0 150` },
    { title: "콤피 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Compy/Compy_Character_BP.Compy_Character_BP'" 0 0 0 150` },
    { title: "다에오돈 (멧돼지) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Daeodon/Daeodon_Character_BP.Daeodon_Character_BP'" 0 0 0 150` },
    { title: "데스웜 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/DeathWorm/DeathWorm_Character_BP.DeathWorm_Character_BP'" 0 0 0 150` },
    { title: "딜로포 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dilo/Dilo_Character_BP.Dilo_Character_BP'" 0 0 0 150` },
    { title: "디메트로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dimetrodon/Dimetro_Character_BP.Dimetro_Character_BP'" 0 0 0 150` },
    { title: "디몰포돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_Character_BP.Dimorph_Character_BP'" 0 0 0 150` },
    { title: "디플로카울루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_Character_BP.Diplocaulus_Character_BP'" 0 0 0 150` },
    { title: "디플로도쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Diplodocus/Diplodocus_Character_BP.Diplodocus_Character_BP'" 0 0 0 150` },
    { title: "다이어베어 (곰) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Direbear/Direbear_Character_BP.Direbear_Character_BP'" 0 0 0 150` },
    { title: "다이어울프 (늑대) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Direwolf/Direwolf_Character_BP.Direwolf_Character_BP'" 0 0 0 150` },
    { title: "도도 (닭 비슷한 새) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP.Dodo_Character_BP'" 0 0 0 150` },
    { title: "도에디쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Doedicurus/Doed_Character_BP.Doed_Character_BP'" 0 0 0 150` },
    { title: "드래곤 (보스) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dragon/Dragon_Character_BP.Dragon_Character_BP'" 0 0 0 150` },
    { title: "아카티나 (달팽이) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Achatina/Achatina_Character_BP.Achatina_Character_BP'" 0 0 0 150` },
    { title: "알로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Allosaurus/Allo_Character_BP.Allo_Character_BP'" 0 0 0 150` },
    { title: "알파 카르노 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Carno/MegaCarno_Character_BP.MegaCarno_Character_BP'" 0 0 0 150` },
    { title: "알파 리드시크티스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Leedsichthys/Alpha_Leedsichthys_Character_BP.Alpha_Leedsichthys_Character_BP'" 0 0 0 150` },
    { title: "알파 메갈로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Megalodon/MEgaMegalodon_Character_BP.MegaMegalodon_Character_BP'" 0 0 0 150` },
    { title: "알파 모사사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP_Mega.Mosa_Character_BP_Mega'" 0 0 0 150` },
    { title: "알파 랩터 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Raptor/MegaRaptor_Character_BP.MegaRaptor_Character_BP'" 0 0 0 150` },
    { title: "알파 티렉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Rex/MegaRex_Character_BP.MegaRex_Character_BP'" 0 0 0 150` },
    { title: "알파 투소테우티스 (알파 크라켄) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Tusoteuthis/Mega_Tusoteuthis_Character_BP.Mega_Tusoteuthis_Character_BP'" 0 0 0 150` },
    { title: "암모나이트 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ammonite/Ammonite_Character.Ammonite_Character'" 0 0 0 150` },
    { title: "앵글러피쉬 (초롱아귀) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Anglerfish/Angler_Character_BP.Angler_Character_BP'" 0 0 0 150` },
    { title: "안킬로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ankylo/Ankylo_Character_BP.Ankylo_Character_BP'" 0 0 0 150` },
    { title: "아라네오 (거미) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Spider-Small/SpiderS_Character_BP.SpiderS_Character_BP'" 0 0 0 150` },
    { title: "아키오프테릭스 (시조새) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Archaeopteryx/Archa_Character_BP.Archa_Character_BP'" 0 0 0 150` },
    { title: "아르젠타비스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP'" 0 0 0 150` },
    { title: "아트로플레우라 (큰 지네) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Arthropluera/Arthro_Character_BP.Arthro_Character_BP'" 0 0 0 150` },
    { title: "바리오닉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_Character_BP.Baryonyx_Character_BP'" 0 0 0 150` },
    { title: "바실로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Basilosaurus/Basilosaurus_Character_BP.Basilosaurus_Character_BP'" 0 0 0 150` },
    { title: "밸제부포 (개구리) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Toad/Toad_Character_BP.Toad_Character_BP'" 0 0 0 150` },
    { title: "브론토사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Sauropod/Sauropod_Character_BP.Sauropod_Character_BP'" 0 0 0 150` },
    { title: "브루드 마더 (거미 보스) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Spider-Large/SpiderL_Character_BP.SpiderL_Character_BP'" 0 0 0 150` },
    { title: "칼리코테리움 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Chalicotherium/Chalico_Character_BP.Chalico_Character_BP'" 0 0 0 150` },
    { title: "카르보네미스 (큰 거북이) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP.Turtle_Character_BP'" 0 0 0 150` },
    { title: "카르노타우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Carno/Carno_Character_BP.Carno_Character_BP'" 0 0 0 150` },
    { title: "카스트로이데스 (비버) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Beaver/Beaver_Character_BP.Beaver_Character_BP'" 0 0 0 150` },
    { title: "해파리 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_Character_BP.Cnidaria_Character_BP'" 0 0 0 150` },
    { title: "실러캔스 (물고기) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP.Coel_Character_BP'" 0 0 0 150` },
    { title: "콤피 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Compy/Compy_Character_BP.Compy_Character_BP'" 0 0 0 150` },
    { title: "다에오돈 (멧돼지) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Daeodon/Daeodon_Character_BP.Daeodon_Character_BP'" 0 0 0 150` },
    { title: "데스웜 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/DeathWorm/DeathWorm_Character_BP.DeathWorm_Character_BP'" 0 0 0 150` },
    { title: "딜로포 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dilo/Dilo_Character_BP.Dilo_Character_BP'" 0 0 0 150` },
    { title: "디메트로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dimetrodon/Dimetro_Character_BP.Dimetro_Character_BP'" 0 0 0 150` },
    { title: "디몰포돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_Character_BP.Dimorph_Character_BP'" 0 0 0 150` },
    { title: "디플로카울루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_Character_BP.Diplocaulus_Character_BP'" 0 0 0 150` },
    { title: "디플로도쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Diplodocus/Diplodocus_Character_BP.Diplodocus_Character_BP'" 0 0 0 150` },
    { title: "다이어베어 (곰) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Direbear/Direbear_Character_BP.Direbear_Character_BP'" 0 0 0 150` },
    { title: "다이어울프 (늑대) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Direwolf/Direwolf_Character_BP.Direwolf_Character_BP'" 0 0 0 150` },
    { title: "도도 (닭 비슷한 새) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP.Dodo_Character_BP'" 0 0 0 150` },
    { title: "도에디쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Doedicurus/Doed_Character_BP.Doed_Character_BP'" 0 0 0 150` },
    { title: "드래곤 (보스) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dragon/Dragon_Character_BP.Dragon_Character_BP'" 0 0 0 150` },
    { title: "큰 벌 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/DungBeetle/DungBeetle_Character_BP.DungBeetle_Character_BP'" 0 0 0 150` },
    { title: "던클리오스테우스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dunkleosteus/Dunkle_Character_BP.Dunkle_Character_BP'" 0 0 0 150` },
    { title: "전기뱀장어 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Eel/Eel_Character_BP.Eel_Character_BP'" 0 0 0 150` },
    { title: "에쿠스 (말) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP.Equus_Character_BP'" 0 0 0 150` },
    { title: "유니콘 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP_Unicorn.Equus_Character_BP_Unicorn'" 0 0 0 150` },
    { title: "아카티나 (달팽이) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Achatina/Achatina_Character_BP.Achatina_Character_BP'" 0 0 0 150` },
    { title: "알로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Allosaurus/Allo_Character_BP.Allo_Character_BP'" 0 0 0 150` },
    { title: "알파 카르노 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Carno/MegaCarno_Character_BP.MegaCarno_Character_BP'" 0 0 0 150` },
    { title: "알파 리드시크티스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Leedsichthys/Alpha_Leedsichthys_Character_BP.Alpha_Leedsichthys_Character_BP'" 0 0 0 150` },
    { title: "알파 메갈로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Megalodon/MEgaMegalodon_Character_BP.MegaMegalodon_Character_BP'" 0 0 0 150` },
    { title: "알파 모사사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP_Mega.Mosa_Character_BP_Mega'" 0 0 0 150` },
    { title: "알파 랩터 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Raptor/MegaRaptor_Character_BP.MegaRaptor_Character_BP'" 0 0 0 150` },
    { title: "알파 티렉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Rex/MegaRex_Character_BP.MegaRex_Character_BP'" 0 0 0 150` },
    { title: "알파 투소테우티스 (알파 크라켄) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Tusoteuthis/Mega_Tusoteuthis_Character_BP.Mega_Tusoteuthis_Character_BP'" 0 0 0 150` },
    { title: "암모나이트 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ammonite/Ammonite_Character.Ammonite_Character'" 0 0 0 150` },
    { title: "앵글러피쉬 (초롱아귀) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Anglerfish/Angler_Character_BP.Angler_Character_BP'" 0 0 0 150` },
    { title: "안킬로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ankylo/Ankylo_Character_BP.Ankylo_Character_BP'" 0 0 0 150` },
    { title: "아라네오 (거미) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Spider-Small/SpiderS_Character_BP.SpiderS_Character_BP'" 0 0 0 150` },
    { title: "아키오프테릭스 (시조새) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Archaeopteryx/Archa_Character_BP.Archa_Character_BP'" 0 0 0 150` },
    { title: "아르젠타비스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Argentavis/Argent_Character_BP.Argent_Character_BP'" 0 0 0 150` },
    { title: "아트로플레우라 (큰 지네) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Arthropluera/Arthro_Character_BP.Arthro_Character_BP'" 0 0 0 150` },
    { title: "바리오닉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Baryonyx/Baryonyx_Character_BP.Baryonyx_Character_BP'" 0 0 0 150` },
    { title: "바실로사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Basilosaurus/Basilosaurus_Character_BP.Basilosaurus_Character_BP'" 0 0 0 150` },
    { title: "밸제부포 (개구리) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Toad/Toad_Character_BP.Toad_Character_BP'" 0 0 0 150` },
    { title: "브론토사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Sauropod/Sauropod_Character_BP.Sauropod_Character_BP'" 0 0 0 150` },
    { title: "브루드 마더 (거미 보스) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Spider-Large/SpiderL_Character_BP.SpiderL_Character_BP'" 0 0 0 150` },
    { title: "칼리코테리움 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Chalicotherium/Chalico_Character_BP.Chalico_Character_BP'" 0 0 0 150` },
    { title: "카르보네미스 (큰 거북이) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Turtle/Turtle_Character_BP.Turtle_Character_BP'" 0 0 0 150` },
    { title: "카르노타우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Carno/Carno_Character_BP.Carno_Character_BP'" 0 0 0 150` },
    { title: "카스트로이데스 (비버) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Beaver/Beaver_Character_BP.Beaver_Character_BP'" 0 0 0 150` },
    { title: "해파리 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Cnidaria/Cnidaria_Character_BP.Cnidaria_Character_BP'" 0 0 0 150` },
    { title: "실러캔스 (물고기) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Coelacanth/Coel_Character_BP.Coel_Character_BP'" 0 0 0 150` },
    { title: "콤피 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Compy/Compy_Character_BP.Compy_Character_BP'" 0 0 0 150` },
    { title: "다에오돈 (멧돼지) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Daeodon/Daeodon_Character_BP.Daeodon_Character_BP'" 0 0 0 150` },
    { title: "데스웜 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/DeathWorm/DeathWorm_Character_BP.DeathWorm_Character_BP'" 0 0 0 150` },
    { title: "딜로포 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dilo/Dilo_Character_BP.Dilo_Character_BP'" 0 0 0 150` },
    { title: "디메트로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dimetrodon/Dimetro_Character_BP.Dimetro_Character_BP'" 0 0 0 150` },
    { title: "디몰포돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dimorphodon/Dimorph_Character_BP.Dimorph_Character_BP'" 0 0 0 150` },
    { title: "디플로카울루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Diplocaulus/Diplocaulus_Character_BP.Diplocaulus_Character_BP'" 0 0 0 150` },
    { title: "디플로도쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Diplodocus/Diplodocus_Character_BP.Diplodocus_Character_BP'" 0 0 0 150` },
    { title: "다이어베어 (곰) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Direbear/Direbear_Character_BP.Direbear_Character_BP'" 0 0 0 150` },
    { title: "다이어울프 (늑대) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Direwolf/Direwolf_Character_BP.Direwolf_Character_BP'" 0 0 0 150` },
    { title: "도도 (닭 비슷한 새) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dodo/Dodo_Character_BP.Dodo_Character_BP'" 0 0 0 150` },
    { title: "도에디쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Doedicurus/Doed_Character_BP.Doed_Character_BP'" 0 0 0 150` },
    { title: "드래곤 (보스) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dragon/Dragon_Character_BP.Dragon_Character_BP'" 0 0 0 150` },
    { title: "큰 벌 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/DungBeetle/DungBeetle_Character_BP.DungBeetle_Character_BP'" 0 0 0 150` },
    { title: "던클리오스테우스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dunkleosteus/Dunkle_Character_BP.Dunkle_Character_BP'" 0 0 0 150` },
    { title: "전기뱀장어 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Eel/Eel_Character_BP.Eel_Character_BP'" 0 0 0 150` },
    { title: "에쿠스 (말) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP.Equus_Character_BP'" 0 0 0 150` },
    { title: "유니콘 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Equus/Equus_Character_BP_Unicorn.Equus_Character_BP_Unicorn'" 0 0 0 150` },
    { title: "바다전갈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Eurypterid/Euryp_Character.Euryp_Character'" 0 0 0 150` },
    { title: "갈리미무스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Gallimimus/Galli_Character_BP.Galli_Character_BP'" 0 0 0 150` },
    { title: "벌 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Bee/Bee_Character_BP.Bee_Character_BP'" 0 0 0 150` },
    { title: "기가노토사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Giganotosaurus/Gigant_Character_BP.Gigant_Character_BP'" 0 0 0 150` },
    { title: "기간토피테쿠스 (빅풋) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Bigfoot/Bigfoot_Character_BP.Bigfoot_Character_BP'" 0 0 0 150` },
    { title: "그리핀 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Griffin/Griffin_Character_BP.Griffin_Character_BP'" 0 0 0 150` },
    { title: "헤스페로니스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Hesperornis/Hesperornis_Character_BP.Hesperornis_Character_BP'" 0 0 0 150` },
    { title: "사람 (남자) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/CoreBlueprints/PlayerPawnTest_Male.PlayerPawnTest_Male'" 0 0 0 150` },
    { title: "사람 (여자) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/CoreBlueprints/PlayerPawnTest_Female.PlayerPawnTest_Female'" 0 0 0 150` },
    { title: "하이에노돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Hyaenodon/Hyaenodon_Character_BP.Hyaenodon_Character_BP'" 0 0 0 150` },
    { title: "이크티오르니스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ichthyornis/Ichthyornis_Character_BP.Ichthyornis_Character_BP'" 0 0 0 150` },
    { title: "이크티오사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dolphin/Dolphin_Character_BP.Dolphin_Character_BP'" 0 0 0 150` },
    { title: "이구아노돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Iguanodon/Iguanodon_Character_BP.Iguanodon_Character_BP'" 0 0 0 150` },
    { title: "카이루쿠 (펭귄) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Kairuku/Kairuku_Character_BP.Kairuku_Character_BP'" 0 0 0 150` },
    { title: "카프로수쿠스 (점프력 좋은 악어) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Kaprosuchus/Kaprosuchus_Character_BP.Kaprosuchus_Character_BP'" 0 0 0 150` },
    { title: "켄트로사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Kentrosaurus/Kentro_Character_BP.Kentro_Character_BP'" 0 0 0 150` },
    { title: "거머리 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Leech/Leech_Character.Leech_Character'" 0 0 0 150` },
    { title: "리드시크티스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Leedsichthys/Leedsichthys_Character_BP.Leedsichthys_Character_BP'" 0 0 0 150` },
    { title: "리오플레우로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Liopleurodon/Liopleurodon_Character_BP.Liopleurodon_Character_BP'" 0 0 0 150` },
    { title: "리스트로사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Lystrosaurus/Lystro_Character_BP.Lystro_Character_BP'" 0 0 0 150` },
    { title: "맘모스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Mammoth/Mammoth_Character_BP.Mammoth_Character_BP'" 0 0 0 150` },
    { title: "만타 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Manta/Manta_Character_BP.Manta_Character_BP'" 0 0 0 150` },
    { title: "만티코어 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Manticore/Manticore_Character_BP.Manticore_Character_BP'" 0 0 0 150` },
    { title: "메갈라니아 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Megalania/Megalania_Character_BP.Megalania_Character_BP'" 0 0 0 150` },
    { title: "메갈로케로스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Stag/Stag_Character_BP.Stag_Character_BP'" 0 0 0 150` },
    { title: "메갈로돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Megalodon/Megalodon_Character_BP.Megalodon_Character_BP'" 0 0 0 150` },
    { title: "메갈로사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Megalosaurus/Megalosaurus_Character_BP.Megalosaurus_Character_BP'" 0 0 0 150` },
    { title: "메가네우라 (잠자리) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Dragonfly/Dragonfly_Character_BP.Dragonfly_Character_BP'" 0 0 0 150` },
    { title: "메가피테쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Gorilla/Gorilla_Character_BP.Gorilla_Character_BP'" 0 0 0 150` },
    { title: "메가테리움 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Megatherium/Megatherium_Character_BP.Megatherium_Character_BP'" 0 0 0 150` },
    { title: "원숭이 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Monkey/Monkey_Character_BP.Monkey_Character_BP'" 0 0 0 150` },
    { title: "미크로랍토르 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Microraptor/Microraptor_Character_BP.Microraptor_Character_BP'" 0 0 0 150` },
    { title: "모사사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Mosasaurus/Mosa_Character_BP.Mosa_Character_BP'" 0 0 0 150` },
    { title: "모스콥스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Moschops/Moschops_Character_BP.Moschops_Character_BP'" 0 0 0 150` },
    { title: "박쥐 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Bat/Bat_Character_BP.Bat_Character_BP'" 0 0 0 150` },
    { title: "수달 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Otter/Otter_Character_BP.Otter_Character_BP'" 0 0 0 150` },
    { title: "오비랍토르 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Oviraptor/Oviraptor_Character_BP.Oviraptor_Character_BP'" 0 0 0 150` },
    { title: "양 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Sheep/Sheep_Character_BP.Sheep_Character_BP'" 0 0 0 150` },
    { title: "파키케팔로사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Pachy/Pachy_Character_BP.Pachy_Character_BP'" 0 0 0 150` },
    { title: "파키리노사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Pachyrhinosaurus/Pachyrhino_Character_BP.Pachyrhino_Character_BP'" 0 0 0 150` },
    { title: "파라케라테리움 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Paraceratherium/Paracer_Character_BP.Paracer_Character_BP'" 0 0 0 150` },
    { title: "파라사우롤로푸스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Para/Para_Character_BP.Para_Character_BP'" 0 0 0 150` },
    { title: "페고메고탁스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Pegomastax/Pegomastax_Character_BP.Pegomastax_Character_BP'" 0 0 0 150` },
    { title: "펠라고르니스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Pelagornis/Pela_Character_BP.Pela_Character_BP'" 0 0 0 150` },
    { title: "피오미아 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Phiomia/Phiomia_Character_BP.Phiomia_Character_BP'" 0 0 0 150` },
    { title: "피닉스 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Phoenix/Phoenix_Character_BP.Phoenix_Character_BP'" 0 0 0 150` },
    { title: "피라냐 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Piranha/Piranha_Character_BP.Piranha_Character_BP'" 0 0 0 150` },
    { title: "플레시오사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Plesiosaur/Plesiosaur_Character_BP.Plesiosaur_Character_BP'" 0 0 0 150` },
    { title: "프로콥토돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Procoptodon/Procoptodon_Character_BP.Procoptodon_Character_BP'" 0 0 0 150` },
    { title: "프테라노돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Ptero/Ptero_Character_BP.Ptero_Character_BP'" 0 0 0 150` },
    { title: "펄모노스콜피어스 (전갈) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Scorpion/Scorpion_Character_BP.Scorpion_Character_BP'" 0 0 0 150` },
    { title: "펄로비아 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Purlovia/Purlovia_Character_BP.Purlovia_Character_BP'" 0 0 0 150` },
    { title: "케찰코아툴루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Quetzalcoatlus/Quetz_Character_BP.Quetz_Character_BP'" 0 0 0 150` },
    { title: "랩터 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Raptor/Raptor_Character_BP.Raptor_Character_BP'" 0 0 0 150` },
    { title: "렉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Rex/Rex_Character_BP.Rex_Character_BP'" 0 0 0 150` },
    { title: "세이버투스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Saber/Saber_Character_BP.Saber_Character_BP'" 0 0 0 150` },
    { title: "연어 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Salmon/Salmon_Character_BP.Salmon_Character_BP'" 0 0 0 150` },
    { title: "사르코수쿠스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Sarco/Sarco_Character_BP.Sarco_Character_BP'" 0 0 0 150` },
    { title: "스피노 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Spino/Spino_Character_BP.Spino_Character_BP'" 0 0 0 150` },
    { title: "스테고사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Stego/Stego_Character_BP.Stego_Character_BP'" 0 0 0 150` },
    { title: "타페자라 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Tapejara/Tapejara_Character_BP.Tapejara_Character_BP'" 0 0 0 150` },
    { title: "테크 파라사우롤로푸스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Para/BionicPara_Character_BP.BionicPara_Character_BP'" 0 0 0 150` },
    { title: "테크 케찰코아툴루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Quetzalcoatlus/BionicQuetz_Character_BP.BionicQuetz_Character_BP'" 0 0 0 150` },
    { title: "테크 랩터 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Raptor/BionicRaptor_Character_BP.BionicRaptor_Character_BP'" 0 0 0 150` },
    { title: "테크 렉스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Rex/BionicRex_Character_BP.BionicRex_Character_BP'" 0 0 0 150` },
    { title: "테크 스테고사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Stego/BionicStego_Character_BP.BionicStego_Character_BP'" 0 0 0 150` },
    { title: "테러버드 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/TerrorBird/TerrorBird_Character_BP.TerrorBird_Character_BP'" 0 0 0 150` },
    { title: "테리지노사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Therizinosaurus/Therizino_Character_BP.Therizino_Character_BP'" 0 0 0 150` },
    { title: "틸라콜레오 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Thylacoleo/Thylacoleo_Character_BP.Thylacoleo_Character_BP'" 0 0 0 150` },
    { title: "티타노보아 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/BoaFrill/BoaFrill_Character_BP.BoaFrill_Character_BP'" 0 0 0 150` },
    { title: "티타노사우루스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/titanosaur/Titanosaur_Character_BP.Titanosaur_Character_BP'" 0 0 0 150` },
    { title: "트리케라톱스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Trike/Trike_Character_BP.Trike_Character_BP'" 0 0 0 150` },
    { title: "삼엽충 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Trilobite/Trilobite_Character.Trilobite_Character'" 0 0 0 150` },
    { title: "트로오돈 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Troodon/Troodon_Character_BP.Troodon_Character_BP'" 0 0 0 150` },
    { title: "투소테우티스 (크라켄) 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Tusoteuthis/Tusoteuthis_Character_BP.Tusoteuthis_Character_BP'" 0 0 0 150` },
    { title: "코뿔소 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/WoollyRhino/Rhino_Character_BP.Rhino_Character_BP'" 0 0 0 150` },
    { title: "예티 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Bigfoot/Yeti_Character_BP.Yeti_Character_BP'" 0 0 0 150` },
    { title: "유티라누스 소환", code: `SPAWNDINO "Blueprint'/Game/PrimalEarth/Dinos/Yutyrannus/Yutyrannus_Character_BP.Yutyrannus_Character_BP'" 0 0 0 150` },
    { title: "뛰는쥐 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Jerboa/Jerboa_Character_BP.Jerboa_Character_BP'" 0 0 0 150` },
    { title: "주전자벌레 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Jugbug/JugBug_Character_BaseBP.JugBug_Character_BaseBP'" 0 0 0 150` },
    { title: "리멘트리아 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Moth/Moth_Character_BP.Moth_Character_BP'" 0 0 0 150` },
    { title: "사마귀 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Mantis/Mantis_Character_BP.Mantis_Character_BP'" 0 0 0 150` },
    { title: "모렐라톱스 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Camelsaurus/camelsaurus_Character_BP.camelsaurus_Character_BP'" 0 0 0 150` },
    { title: "골렘 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/RockGolem/RockGolem_Character_BP.RockGolem_Character_BP'" 0 0 0 150` },
    { title: "자갈 골렘 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/RockGolem/RubbleGolem_Character_BP.RubbleGolem_Character_BP'" 0 0 0 150` },
    { title: "가시드래곤 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/SpineyLizard/SpineyLizard_Character_BP.SpineyLizard_Character_BP'" 0 0 0 150` },
    { title: "독수리 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Vulture/Vulture_Character_BP.Vulture_Character_BP'" 0 0 0 150` },
    { title: "와이번 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Base.Wyvern_Character_BP_Base'" 0 0 0 150` },
    { title: "불 와이번 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Fire.Wyvern_Character_BP_Fire'" 0 0 0 150` },
    { title: "번개 와이번 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Lightning.Wyvern_Character_BP_Lightning'" 0 0 0 150` },
    { title: "독 와이번 소환", code: `SPAWNDINO "Blueprint'/Game/ScorchedEarth/Dinos/Wyvern/Wyvern_Character_BP_Poison.Wyvern_Character_BP_Poison'" 0 0 0 150` },
    { title: "얼음 와이번 소환", code: `SPAWNDINO "Blueprint'/Game/Mods/Ragnarok/Custom_Assets/Dinos/Wyvern/Ice_Wyvern/Ragnarok_Wyvern_Override_Ice.Ragnarok_Wyvern_Override_Ice'" 0 0 0 150` },
    { title: "알파 바실리스크 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Basilisk/MegaBasilisk_Character_BP.MegaBasilisk_Character_BP'" 0 0 0 150` },
    { title: "알파 카르키노스 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Crab/MegaCrab_Character_BP.MegaCrab_Character_BP'" 0 0 0 150` },
    { title: "알파 리퍼 킹 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Nameless/MegaXenomorph_Character_BP_Male_Surface.MegaXenomorph_Character_BP_Male_Surface'" 0 0 0 150` },
    { title: "바실리스크 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Basilisk/Basilisk_Character_BP.Basilisk_Character_BP'" 0 0 0 150` },
    { title: "벌브독 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/LanternPug/LanternPug_Character_BP.LanternPug_Character_BP'" 0 0 0 150` },
    { title: "페더라이트 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/LanternBird/LanternBird_Character_BP.LanternBird_Character_BP'" 0 0 0 150` },
    { title: "빛벌레 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Lightbug/Lightbug_Character_BaseBP.Lightbug_Character_BaseBP'" 0 0 0 150` },
    { title: "글로우테일 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/LanternLizard/LanternLizard_Character_BP.LanternLizard_Character_BP'" 0 0 0 150` },
    { title: "카르키노스 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Crab/Crab_Character_BP.Crab_Character_BP'" 0 0 0 150` },
    { title: "칠성장어 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Lamprey/Lamprey_Character.Lamprey_Character'" 0 0 0 150` },
    { title: "네임리스 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/ChupaCabra/ChupaCabra_Character_BP.ChupaCabra_Character_BP'" 0 0 0 150` },
    { title: "네임리스 퀸 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP.Xenomorph_Character_BP'" 0 0 0 150` },
    { title: "레비져 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/CaveWolf/CaveWolf_Character_BP.CaveWolf_Character_BP'" 0 0 0 150` },
    { title: "리퍼킹 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP_Male.Xenomorph_Character_BP_Male'" 0 0 0 150` },
    { title: "리퍼 퀸 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Nameless/Xenomorph_Character_BP_Female.Xenomorph_Character_BP_Female'" 0 0 0 150` },
    { title: "락 드레이크 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/RockDrake/RockDrake_Character_BP.RockDrake_Character_BP'" 0 0 0 150` },
    { title: "룰 렛 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/MoleRat/MoleRat_Character_BP.MoleRat_Character_BP'" 0 0 0 150` },
    { title: "씨커 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/Pteroteuthis/Pteroteuthis_Char_BP.Pteroteuthis_Char_BP'" 0 0 0 150` },
    { title: "샤이니혼 소환", code: `SPAWNDINO "Blueprint'/Game/Aberration/Dinos/LanternGoat/LanternGoat_Character_BP.LanternGoat_Character_BP'" 0 0 0 150` },
    { title: "알파 킹 타이탄 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/KingKaiju/KingKaiju_Character_BP_Alpha.KingKaiju_Character_BP_Alpha'" 0 0 0 150` },
    { title: "디펜스 유닛 (방어 유닛) 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Tank/Defender_Character_BP.Defender_Character_BP'" 0 0 0 150` },
    { title: "더스트 타이탄 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/DesertKaiju/DesertKaiju_Character_BP.DesertKaiju_Character_BP'" 0 0 0 150` },
    { title: "인포서 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Enforcer/Enforcer_Character_BP.Enforcer_Character_BP'" 0 0 0 150` },
    { title: "포레스트 타이탄 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/ForestKaiju/ForestKaiju_Character_BP.ForestKaiju_Character_BP'" 0 0 0 150` },
    { title: "포레스트 와이번 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/ForestKaiju/Minion/Wyvern_Character_BP_Fire_Minion.Wyvern_Character_BP_Fire_Minion'" 0 0 0 150` },
    { title: "갓챠 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Gacha/Gacha_Character_BP.Gacha_Character_BP'" 0 0 0 150` },
    { title: "갓챠클로스 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Gacha/Gacha_Claus_Character_BP.Gacha_Claus_Character_BP'" 0 0 0 150` },
    { title: "가스백 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/GasBag/GasBags_Character_BP.GasBags_Character_BP'" 0 0 0 150` },
    { title: "아이스 타이탄 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/IceKaiju/IceKaiju_Character_BP.IceKaiju_Character_BP'" 0 0 0 150` },
    { title: "마나가르마 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/IceJumper/IceJumper_Character_BP.IceJumper_Character_BP'" 0 0 0 150` },
    { title: "메가 메카 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Mek/MegaMek_Character_BP.MegaMek_Character_BP'" 0 0 0 150` },
    { title: "메카 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Mek/Mek_Character_BP.Mek_Character_BP'" 0 0 0 150` },
    { title: "스카웃 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Scout/Scout_Character_BP.Scout_Character_BP'" 0 0 0 150` },
    { title: "눈 부엉이 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Owl/Owl_Character_BP.Owl_Character_BP'" 0 0 0 150` },
    { title: "벨로나사우르스 소환", code: `SPAWNDINO "Blueprint'/Game/Extinction/Dinos/Spindles/Spindles_Character_BP.Spindles_Character_BP'" 0 0 0 150` }
];


// 명령어 리스트 생성
function renderCommands() {
    const commandList = document.getElementById("commandList");
    if (!commandList) {
        console.error("commandList 요소를 찾을 수 없습니다. HTML 파일에 ID가 'commandList'인 요소를 추가하세요.");
        return;
    }
    commandList.innerHTML = ""; // 기존 내용 초기화
    commands.forEach(command => {
        const commandItem = document.createElement("div");
        commandItem.classList.add("command-item");

        // 20자 이상일 경우 줄이기
        const displayCode = command.code.length > 20
            ? `${command.code.substring(0, 20)}...`
            : command.code;

        commandItem.innerHTML = `
            <p><strong>${command.title}:</strong> ${displayCode}</p>
        `;
        commandItem.addEventListener("click", () => copyCommand(command.code));
        commandList.appendChild(commandItem);
    });
}

    // 명령어 복사 기능
    function copyCommand(code) {
        navigator.clipboard.writeText(code).then(() => {
            showToast(`명령어가 복사되었습니다: ${code}`);
        });
    }

    // 토스트 메시지 표시
    function showToast(message) {
        const toast = document.getElementById('toast');
        toast.textContent = message;
        toast.classList.add('show');
        setTimeout(() => {
            toast.classList.remove('show');
        }, 3000); // 3초 후에 메시지 숨김
    }

// 명령어 검색 기능
document.getElementById("commandSearch").addEventListener("input", function () {
    const searchValue = this.value.toLowerCase();
    const filteredCommands = commands.filter(command =>
        command.title.toLowerCase().includes(searchValue) ||
        command.code.toLowerCase().includes(searchValue)
    );
    const commandList = document.getElementById("commandList");
    commandList.innerHTML = ""; // 기존 내용 초기화
    filteredCommands.forEach(command => {
        const commandItem = document.createElement("div");
        commandItem.classList.add("command-item");

        // 20자 이상일 경우 줄이기
        const displayCode = command.code.length > 20
            ? `${command.code.substring(0, 20)}...`
            : command.code;

        commandItem.innerHTML = `
            <p><strong>${command.title}:</strong> ${displayCode}</p>
        `;
        commandItem.addEventListener("click", () => copyCommand(command.code));
        commandList.appendChild(commandItem);
    });
});

// 초기 렌더링
document.addEventListener("DOMContentLoaded", () => {
    renderCommands();
});
