const  generalCommands= [
    { title: "모아 키", code: "CHEAT gfi key 99999999 1 0" },
    { title: "무적", code: "god" },
    { title: "투명화", code: "enemyinvisible true" },
    { title: "투명화 (비활성화)", code: "enemyinvisible false" },
    { title: "경험치", code: "addexperience 10000 0 1" },
    { title: "스탯 무한", code: "infinitestats" },
    { title: "플레이어 앞 공룡 테이밍", code: "dotame" },
    { title: "플레이어 앞 공룡 테이밍 + 안장 없이 탑승 가능", code: "forcetame" },
    { title: "원소 100개", code: "gfi Element 100 0 0" },
    { title: "포드 냉장고", code: "gfi CryoFridge 1 1 0" },
    { title: "크라이포드", code: "gfi EmptyCryopod 100" },   //불가
    { title: "테크 발전기", code: "gfi TekGenerator 1 1 0" },
    { title: "날기", code: "fly" },
    { title: "유령화", code: "ghost" },
    { title: "걷기", code: "walk" },
    { title: "모든 앵그램 해금", code: "giveengrams" },
    { title: "강화 무적", code: "gmbuff" },
    { title: "야생 공룡 리셋", code: "DestroyWildDinos" },
    { title: "모든 공룡 리셋", code: "Destroyallenemies" },
    { title: "아기 공룡 성장 수치 조절", code: "SetBabyAge 1" },
    { title: "공룡 각인 수치 설정", code: "SetImprintQuality 1" },
    { title: "공룡들 움직임 멈춤", code: "playersonly" },
    { title: "총알 무제한", code: "toggleinfiniteammo" },
    { title: "모든 자원 얻기", code: "giveresources" },
    { title: "현재 내 버프 지우기", code: "ClearMyBuffs" },
    { title: "테크 슈트 입기", code: "GiveArmorSet Tek 20" },
    { title: "사막 슈트 입기", code: "GiveArmorSet Desert 20" },
    { title: "방호복 슈트 입기", code: "GiveArmorSet Hazard 20" },
    { title: "키틴 슈트 입기", code: "GiveArmorSet Chitin 20" },
    { title: "가죽 슈트 입기", code: "GiveArmorSet Hide 20" },
    { title: "길리 슈트 입기", code: "GiveArmorSet Ghillie 20" },
    { title: "수쿠버 슈트 입기", code: "GiveArmorSet Scuba 20" },
    { title: "방탄 슈트 입기", code: "GiveArmorSet Metal 20" },
    { title: "모피 슈트 입기", code: "GiveArmorSet Fur 20" },
    { title: "진압복 슈트 입기", code: "GiveArmorSet Riot 20" },
    { title: "천 슈트 입기", code: "GiveArmorSet Cloth 20" },
    { title: "무기 세트 1", code: "GiveWeaponSet 0 20" },
    { title: "무기 세트 2", code: "GiveWeaponSet 1 20" },
    { title: "무기 세트 3", code: "GiveWeaponSet 2 20" },
    { title: "무기 세트 4", code: "GiveWeaponSet 3 20" },
    { title: "아이템 세트 1", code: "GiveItemSet 0" },
    { title: "아이템 세트 2", code: "GiveItemSet 1" },
    { title: "아이템 세트 3", code: "GiveItemSet 2" },
    { title: "아이템 세트 4", code: "GiveItemSet 3" },
    { title: "음식 세트", code: "GiveItemSet food" },
    { title: "수통", code: "GiveItemSet water" },
    { title: "브루 세트", code: "GiveItemSet brews" },
    { title: "관찰자 모드 활성화(주의)", code: "Enablespectator" },
    { title: "관찰자 모드 비활성화", code: "Stopspectating" },
    { title: "바라보는 방향에 경험치 주기", code: "GiveExpToTarget 10000 0 1" },
    { title: "자신에게 데미지 주기", code: "hurtme 1000" },
    { title: "자신에게 힐 하기", code: "hurtme -1000" },
    { title: "바라보는 타겟 죽이기", code: "kill" },
    { title: "범위 근처 모든 공룡 죽이기", code: "KillAOE dinos 3000" },
    { title: "범위 근처 야생 공룡 죽이기", code: "KillAOE wild 3000" },
    { title: "범위 근처 길들인 공룡 죽이기", code: "KillAOE tamed 3000" },
    { title: "범위 근처 플레이어 죽이기", code: "KillAOE players 3000" },
    { title: "범위 근처 구조물 부수기", code: "KillAOE stuctures 3000" },
    { title: "1인칭에서 무기 숨기기", code: "ToggleGun" },
    { title: "서버에 데미지 텍스트 표시", code: "ToggleDamageNumbers" },
    { title: "게임 속도", code: "Slomo 4" },
    { title: "인게임 시간 변경", code: "settimeofday 13:30" },
    { title: "범위안 안장없이 테이밍", code: "ForceTameAOE 2000" },
    { title: "알 즉시 부화", code: "hatchegg" },
];


export default generalCommands;